### ISSUE TITLE
Error when trying to run with "npm run start"

### ISSUE THREAD

**Issue by RisottoNacho** [apache/age-viewer#166]
**Description of the bug**
After executing "npm run setup" I try to run "npm run start" but get the following error:
```
Starting the development server...

/home/nacho/Documentos/GitHub/age-viewer/frontend/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/nacho/Documentos/GitHub/age-viewer/frontend/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/nacho/Documentos/GitHub/age-viewer/frontend/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/nacho/Documentos/GitHub/age-viewer/frontend/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/nacho/Documentos/GitHub/age-viewer/frontend/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/nacho/Documentos/GitHub/age-viewer/frontend/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/nacho/Documentos/GitHub/age-viewer/frontend/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/nacho/Documentos/GitHub/age-viewer/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/nacho/Documentos/GitHub/age-viewer/frontend/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.1
ERROR: "front" exited with 1.
```
I updated to the latest pm2 version but the problem still persists. The same error pops if I try to execute "npm run build-front ".

**To Reproduce**
1. Run "npm run setup" 
2.  Run "npm run start" 

**Desktop**
 - OS: Ubuntu 22.04
 - Node.js v18.17.1

**Comment by tsmanuelanton** [comment]
you can fix this executing before `export NODE_OPTIONS=--openssl-legacy-provider`
