### ISSUE TITLE
Error 'digital envelope' when starting 1.0.0-rc2 AGE Viewer 

### ISSUE THREAD

**Issue by amilenovic** [apache/age-viewer#90]
**Describe the bug**
Cannot start AGE Viewer 1.0.0-rc2, by following README.md.
According to https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported , I added ```--openssl-legacy-provider``` in frontend/package.json script start, but didn't work.

**To Reproduce**
1. npm run setup
2. npm run start

**Expected behavior**

**Screenshots**
```
Node.js v18.12.1
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\workspace\tools\age-viewer\frontend\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\workspace\tools\age-viewer\frontend\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\workspace\tools\age-viewer\frontend\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\workspace\tools\age-viewer\frontend\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\workspace\tools\age-viewer\frontend\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\workspace\tools\age-viewer\frontend\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\workspace\tools\age-viewer\frontend\node_modules\loader-runner\lib\LoaderRunner.js:214:10) 
    at iterateNormalLoaders (D:\workspace\tools\age-viewer\frontend\node_modules\loader-runner\lib\LoaderRunner.js:221:10) 
D:\workspace\tools\age-viewer\frontend\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\workspace\tools\age-viewer\frontend\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\workspace\tools\age-viewer\frontend\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\workspace\tools\age-viewer\frontend\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\workspace\tools\age-viewer\frontend\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\workspace\tools\age-viewer\frontend\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\workspace\tools\age-viewer\frontend\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\workspace\tools\age-viewer\frontend\node_modules\loader-runner\lib\LoaderRunner.js:111:13)     
    at D:\workspace\tools\age-viewer\frontend\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
ERROR: "front" exited with 1.
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: 108.0.1462.54

**Additional context**
I use Node.js v18.12.1

**Comment by Nimra-1234** [comment]
Age Viewer is not compatible with node version 18.12.1
As already written in the description you should use node v14.16. 
This will work perfectly.
@amilenovic

**Comment by amilenovic** [comment]
yes, you are right. I downgraded to 14.16.1 and works fine, thanks.

Maybe it is a good idea to create an ENCHANCEMENT task, to keep up with later versions of Node.

**Comment by Nimra-1234** [comment]
Yes you are right. @amilenovic
